"""Initial migration

Revision ID: 0296d80ee62f
Revises: 
Create Date: 2023-11-01 14:30:34.260796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0296d80ee62f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('available')

    # ### end Alembic commands ###
